services:
  pm_scan.services.transcode_service:
    class: PM\ScanBundle\Services\TranscodeService
    arguments:
      - "%transcode_threads%"
      - "%transcode_video_codec%"
      - "%transcode_video_audio_codec%"
      - "%transcode_video_audio_language%"
      - "%transcode_video_container%"